### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by ERodrigoGuz** [ERodrigoGuz/ERodrigoGuz.github.io#1]
**Descripción**
Crear el encabezado del CV

**Mockup**
![image](https://user-images.githubusercontent.com/100477289/174448427-146df2b2-9b2f-4372-9be8-66b3412edc70.png)

**Pruebas**

- [x] Debería de imprimir Nombre: **Edgar Rodrigo Silencio Guzmán**
- [x] Debería de imprimir Titulo académico: **Ingeniero en Sistemas Computacionales**
- [x] Debería de imprimir Objetivo Profesional: **Crear productos y servicios en software de calidad**
- [x] Debería de imprimir la foto de perfil: 
![Sin título](https://user-images.githubusercontent.com/100477289/174448642-699fda7e-6035-43e5-8a80-370acd683008.jpg)

- [x] Debería mostrar Email: **ing.edgarod_guzman@hotmail.com**
- [x] Debería de mostrar el numero de telefono: **Tel. 2721888221**
- [x] Debería de mostrar la ciudad: **Orizaba, Veracruz, Mex**
- [x] Debería de mostrar redes sociales(Facebook): **http://www.facebook.com/RodrigoGuzman**

**Comment by Jonathantg94** [comment]
se vuelve abrir por que se cerro por error

**Comment by ERodrigoGuz** [comment]
se cerro por error de envió a main
